### ISSUE TITLE
Allow colors to be set to unicode in Python 2

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#103]
In Python 2, this fails with unicode strings:

```
        if isinstance(value, str) or (isinstance(value, tuple) and len(value) == 3):
```

(this is in the color trait code). We should use ``isinstance(value, six.string_types)`` instead of ``isinstance(value, str)`` so that unicode strings work.

**Comment by ojustino** [comment]
Is this one fixed now?

**Comment by astrofrog** [comment]
Yes it should be, thanks!
