### ISSUE TITLE
Edit FITS objects once loaded

### ISSUE THREAD

**Issue by ojustino** [WorldWideTelescope/pywwt#113]
(I'm opening this issue so we have it in the same place as the others.) It would be good to find a way to apply stretch and normalization to FITS images, whether through the API or other means.

**Comment by ojustino** [comment]
@astrofrog I know you'll be on holiday soon, but are you thinking there will be no work on this feature between now and AAS? It seems this feature is somewhat behind schedule. The pyWWT tutorial is advertised as covering FITS work as well, so my preparation is similarly delayed.

I'll definitely try to work with Jonathan's comments, but I'm running low on hours and don't know pyWWT's FITS architecture very intimately. As you were the one who set it up, a quick prognosis on how far you think we can get in the remaining weeks would be much appreciated.

**Comment by astrofrog** [comment]
Implemented in https://github.com/WorldWideTelescope/pywwt/pull/188
