### ISSUE TITLE
Crosshair doesn't work in WebGL SDK

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#116]
The crosshair which used to be on by default has disappeared in the WebGL version and it isn't possible to add it back via the SDK at the moment.

**Comment by astrofrog** [comment]
Interestingly it seems the crosshairs do work on Windows, just not Mac/Linux

**Comment by pkgw** [comment]
@thewebkid tackled this and I believe this is fixed now — can you confirm when you get the chance, @astrofrog ?

**Comment by astrofrog** [comment]
Yes this is fixed!
