### ISSUE TITLE
Polygon fill depends on direction

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#118]
As described in https://github.com/WorldWideTelescope/wwt-web-client/issues/181, filling doesn't work for clockwise polygons.

**Comment by pkgw** [comment]
As per @astrojonathan's comments, this looks to be a low-level issue that is not going to be "fixed" in any straightforward manner. Do you remember what use case brought this up? Do we just need the docs to specify the fill rule?

**Comment by astrofrog** [comment]
I think this just came up when I manually tried to specify a polygon in clockwise order. Indeed this is now a documentation issue rather than a bug.

**Comment by ojustino** [comment]
I wrote a preliminary addition to the docs that talks about this in #144.
