### ISSUE TITLE
Circle radius not set upon initialization

### ISSUE THREAD

**Issue by ojustino** [WorldWideTelescope/pywwt#119]
When creating a circle, the radius of the resulting annotation is 4 degrees no matter what radius I put in the original call (`circle = wwt.add_circle(center, radius=...)`). Changing afterward through `circle.radius = ...` works, but it would be good if this extra step wasn't necessary.

**Comment by ojustino** [comment]
I don't know if it was checked earlier, but this doesn't happen for me anymore. There's no difference in size between pixels and degrees, though.

**Comment by astrofrog** [comment]
I'm going to close this as the issue about radii is discussed here: https://github.com/WorldWideTelescope/pywwt/issues/115
