### ISSUE TITLE
Pywwt launch problems

### ISSUE THREAD

**Issue by hickst** [WorldWideTelescope/pywwt#121]
I'm trying to launch pywwt within a Conda environment and it's not displaying the wwt object, contrary to the docs at (https://pywwt.readthedocs.io/en/latest/jupyter.html). Here's what I am doing:

Create a new Conda environment ("wwt") and install pywwt in it:

conda create -n wwt python=3.6
conda activate wwt
conda install -c conda-forge jupyterlab
conda install -c wwt pywwt
jupyter lab --no-browser
// open new Chrome browser window -- copy/paste URL from JupyterServer
// JupyterLab starts, open Python3 notebook, try to follow pywwt docs for "Using the Jupyter Widget"

JupyterLab starts up, pywwt imports are successful; wwt object is created but nothing displays, contrary to the documentation. The wwt object appears to be good: that is, I can do things like
`wwt.available_layers` and get a valid response.

Perhaps, I am forgetting to install some display library that's needed by the plugin?

**Comment by astrofrog** [comment]
@hickst - the current released version of pywwt is not compatible with Jupyter lab yet. Can you check if it works fine in the notebook? We'll release a new version soon that is compatible with Jupyter lab

**Comment by hickst** [comment]
@astrofrog Yes, pywwt seems to work as documented with Jupyter Notebook. There were a couple of small server errors, seemingly related to missing image files:
```
[W 15:23:03.512 NotebookApp] 404 GET /nbextensions/pywwt/sunCorona.png (127.0.0.1) 11.40ms referer=http://localhost:8888/nbextensions/pywwt/wwt.html
[W 15:23:03.517 NotebookApp] 404 GET /nbextensions/pywwt/earth.jpg (127.0.0.1) 1.63ms referer=http://localhost:8888/nbextensions/pywwt/wwt.html
```
