### ISSUE TITLE
WebGL warnings

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#134]
I see a lot of warnings on MacOS X related to WebGL:

```
[.WebGL-0x7f8d8f24c000]RENDER WARNING: there is no texture bound to the unit 0
[.WebGL-0x7f8d8f24c000]RENDER WARNING: there is no texture bound to the unit 0
[.WebGL-0x7f8d8f24c000]RENDER WARNING: there is no texture bound to the unit 0
[.WebGL-0x7f8d8f24c000]RENDER WARNING: there is no texture bound to the unit 0
[.WebGL-0x7f8d8f24c000]RENDER WARNING: there is no texture bound to the unit 0
[.WebGL-0x7f8d8f24c000]RENDER WARNING: there is no texture bound to the unit 0
[.WebGL-0x7f8d8f24c000]RENDER WARNING: there is no texture bound to the unit 0
```

This can be reproduced even with just a simple HTML page with the web client, and is unrelated to Python.

**Comment by astrojonathan** [comment]
Not sure this is possible to avoid. It happens when HTML has not downloaded textures yet, it is send from the shader code and does not let us know where in the script code this was generated. Not sure if this is avoidable, it is a warning, not an error per say.

**Comment by astrojonathan** [comment]
Ok. I fixed this in the checkin in the WWT branch. I used an empty 1x1 texture to substitute for textures that were asynchronously loading, since they report as null until they are loaded.

**Comment by astrofrog** [comment]
I can confirm this is now fixed and have copied over the latest staged JS file to the gh-pages branch here.
