### ISSUE TITLE
Implement transparency for layers

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#142]
We should include an 'alpha' trait for layers

**Comment by astrofrog** [comment]
It looks like transparency is currently ignored on the WWT side - for instance, if I set the color with:

```js
layer.set_color(wwtlib.Color.fromSimpleHex('33ff00aa'))
```

then the color is correct but there is no transparency (the first two bytes should be the transparency)

**Comment by astrojonathan** [comment]
layer.set_opacity(float value) is the correct setting for layer transparency. Some layers will allow color to mix in with opacity, but not always. If Opacity is supported, it should be thru the opacity property.

**Comment by astrofrog** [comment]
This is indeed fixed - PR for PyWWT coming shortly
