### ISSUE TITLE
add_data_layer guesses wrong lat/lon columns for my Earth-centered dataset

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/pywwt#154]
I have been playing around with visualizing the "Kent Puget Sound Flow Model" dataset, [available as an Excel spreadsheet here](http://worldwidetelescope.org/Community#/ContentDetail/892), with pywwt.

Here's the header and first row as CSV:

```
lat,lon,depth,color,datetime,mag
48.157,-122.79,0.261287460327148,cyan,1/1/2010 0:00,0.01
```

If I load this up as a table and add it as a data layer through pywwt without explicitly assigning `lat_att` and `lon_att`, the code ends up guessing `lat_att = 'lon'` and `'lon_att = 'lat'`! Kind of a funny failure mode.

I believe the problem is [here](https://github.com/WorldWideTelescope/pywwt/blob/master/pywwt/layers.py#L218-L222) in the code. If the column names aren't given, it defaults to assigning `lon_att` to the first (well, zero'th) column and `lat_att` to the second. That makes sense if your data start `ra,dec,...`, but it doesn't here.

IMO the best fix would be to look at the actual column names and apply some simple heuristics: e.g., set the longitude column to anything name `lon`, `longitude`, `ra`, etc. Perhaps also issue a warning, and use the current guessing scheme, if none of the heuristics come through.

**Comment by astrofrog** [comment]
I agree it would be good to have some kind of heuristics 👍
