### ISSUE TITLE
Remove `>>> ` prefixes in sample code in the docs?

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/pywwt#162]
The RST source for the docs currently shows sample code like this:

```
by the :func:`matplotlib.colors.to_hex` function from Matplotlib::

    >>> wwt.constellation_boundary_color = 'azure'
    >>> wwt.constellation_figure_color = '#D3BC8D'
    >>> wwt.constellation_selection_color = (1, 0, 1)
```

This suggests that the commands are to be typed interactively, which is good, but it makes copy/paste directly into a notebook tedious, since you have to get rid of the `>>>`s.

I think it's OK just to get rid of them altogether. As rendered on readthedocs, I think the code will look just as reasonable without the prefixing.

If we really want to maintain the prefixing, we could look into CSS magic that will show the `>>>` but not make it part of the region that gets copy/pasted — I know this is possible (e.g. line numbers in GitHub source code listings), but I don't know exactly how it's implemented.

**Comment by astrofrog** [comment]
There is an astropy extension that makes it so that the >>> can be easily removed, I can look into how to use it here.

**Comment by ojustino** [comment]
Now that the "Hide/Show prompt" option is available in the docs' code boxes, is this issue resolved?

**Comment by pkgw** [comment]
Yes.
