### ISSUE TITLE
Layers docs: huge points in earthquakes sample

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/pywwt#163]
When I do the earthquakes sample in the layers docs, the individual points are made absolutely huge, resulting in the entire Earth being covered by big fuzzy blobs:

![screenshot from 2018-12-22 17-33-59](https://user-images.githubusercontent.com/59598/50379157-ccb1ef00-060f-11e9-9e14-a69b6ca2ada5.png)

The `size_scale` parameter here is 10. Setting it to 0.1 gives me something more reasonable.

I'm on Linux/Firefox — is this OS/browser dependent?

**Comment by astrofrog** [comment]
I think this will be fixed by #165

**Comment by astrofrog** [comment]
Actually this was due to WWT trying to guess assignments of columns, and I've fixed this in https://github.com/WorldWideTelescope/pywwt/pull/167
