### ISSUE TITLE
Read the Docs (latest) needs to be updated

### ISSUE THREAD

**Issue by hickst** [WorldWideTelescope/pywwt#178]
The 'latest' Read the Docs (b8a7c870) installation page is not sufficient to correctly install PyWWT for JupyterLabs. I found the missing info in https://github.com/WorldWideTelescope/pywwt/blob/master/docs/installation.rst, which is newer than the Read the Docs version.

**Comment by astrofrog** [comment]
Thanks for the report! I'm seeing issues in the build that appear to be due to some kind of RTD problem - I've reported it at https://github.com/rtfd/readthedocs.org/issues/5133

**Comment by astrofrog** [comment]
Fixed: https://pywwt.readthedocs.io/en/latest/installation.html#using-jupyter-lab
