### ISSUE TITLE
How to input geometry into WWT WindowsClient

### ISSUE THREAD

**Issue by qu123xxx** [WorldWideTelescope/pywwt#182]
I want to input some geometry data layers into WWT WindowsClient with pywwt.

e.g. Linestring(192.306622249 83.412894378,212.212193931 77.547512943,216.881430633 75.695992129,222.676357498 74.155503937,230.182150167 71.834016547)

There are hundreds of file like this so I can't do it manually. 

When I use "new_layer()" it can not work. I read the documentation find it is not support column name "geometry".

When I use "load()" load a csv file it always pop up "Data Visualization Layer" window , so I have to click "Finish" in the window that I can input the next layer.

My question is How to input geometry data show above without pop up "Data Visualization Layer" window .

**Comment by pkgw** [comment]
@astrofrog @ojustino Do either of you have any insight into this one? Is it possible that there might be a way to wire up the `geometry` column somewhere such that this could start working?

**Comment by ojustino** [comment]
@qu123xxx I'm personally not familiar with the Windows client, so I'm not sure how to help in that context and haven't yet found someone who can. (That was part of the delay, so thank you for your patience.) Would you be comfortable using the Qt or Jupyter versions of `pywwt`? 

If so -- it seems like you would like to draw several rectangles on the sky, which is possible through the [`add_polygon`](https://pywwt.readthedocs.io/en/latest/annotations.html#polygons) method. 

You would just need to find a way to convert your list of `Linestring` positions into the Astropy `SkyCoord` that the function uses to draw your shapes. As the link shows, there are also a few customizable properties like color and line width that you can edit to your liking.

How does that sound as a start?

**Comment by qu123xxx** [comment]
@ojustino Thank you for your reply. I can provide some information about this topic.
The `WWT EXCEL ADDIN` was a way to wire up the  `geometry` column without pop up "Data Visualization Layer" window. But it is now unavailable because of a not know Windows Security Update for Office.

Maybe you can learn some way from it to make it work in `pywwt`

I‘m afraid I can't use Qt or Jupyter versions of `pywwt` because I have to make a tour in Windows Client , and export a WWT Layer File. 

I also have time to wait or solve this problem ,because I find some tour in the community of WWT also use  `linestring` or  `TEXT` to visualize some data. For example  
http://www.worldwidetelescope.org/Community/#/ContentDetail/63

So I think if pywwt can achieve this function, users can use it to visualize more kinds of data.

**Comment by ojustino** [comment]
@qu123xxx I see. It's good that you found a workaround, and we'll consider how `pywwt` could help with this kind of thing in the future.

**Comment by qu123xxx** [comment]
Thank you :satisfied:
