### ISSUE TITLE
Widget not working in fresh BinderHub+JupyterLab builds

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/pywwt#226]
If you go to <https://bit.ly/wwt-binder03>, the pywwt widget doesn't work inside the notebook anymore.

I can reproduce locally with `jupyter-repo2docker https://github.com/WorldWideTelescope/pywwt-notebooks`, which builds and runs an image using the same framework as BinderHub. (repo2docker boots up the Jupyter server and prints out the URL to connect to; you have to load that, then alter the URL path to read `/lab` to load up the Lab environment as opposed to classic Jupyter.)

In my browser debug console, I get:

```
Plugin 'pywwt' failed to activate.
Error: "No provider for: jupyter.extensions.jupyterWidgetRegistry."
```

The widget still works inside JupyterLab on my personal machine. Comparing the installed packages, I see that I only have `jupyter-core` version 4.4.0, while the repo2docker build has version 4.5.0. The next thing I will try will be to force an older version and see if that makes the problem go away.

**Comment by pkgw** [comment]
Nope — a test build with jupyter-core 4.4.0 has the same problem.

**Comment by pkgw** [comment]
It *does* work if I just point the build to `WorldWideTelescope/pywwt@master`, as opposed to the 0.6.1 release, which is what `pywwt-notebooks@master` currently points at. So I think we ought to make a new pywwt release.

**Comment by ojustino** [comment]
The widget works for me now that the new release is out.

**Comment by pkgw** [comment]
Yup, this is solved.
