### ISSUE TITLE
Expose option to control units of circle radius

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#23]
Currently the radius of the circle annotations is in display units but I think there is a way to specify it in arcsec (need to check WWT SDK docs)

**Comment by ojustino** [comment]
The docs say that if [skyRelative](https://worldwidetelescope.gitbooks.io/worldwide-telescope-web-control-script-reference/content/webcontrolobjects.html#circle-skyrelative-property) is `True`. Does fixing this involve anything more than changing `skyRelative`'s default value to `True`, then?

**Comment by astrofrog** [comment]
Done in #26
