### ISSUE TITLE
PyWWT freezes when switching to 3D view

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#304]
The following example freezes for me:

```python
from pywwt.qt import WWTQtClient
wwt = WWTQtClient(block_until_ready=True)
wwt.set_view('milky way')
wwt.wait()
```

By freezes I mean that I just see:

<img width="752" alt="Screenshot 2021-07-21 at 16 53 51" src="https://user-images.githubusercontent.com/314716/126520012-2680a026-530f-44c1-bdb1-9095cc66be4a.png">

and am then unable to pan/zoom etc. The terminal shows:

```
Uncaught TypeError: Cannot read property 'z' of undefined (level=2, line_number=22800, source_id=https://web.wwtassets.org/engine/7/wwtsdk.js)
```

I am on MacOS X Big Sur on an M1 laptop but I doubt that should make any difference since the error comes from the SDK js file.

**Comment by pkgw** [comment]
Are you using the absolute latest pywwt? I just (few hours ago) landed some changes to harmonize the way that Qt and Jupyter drive the widget, using the "app" model, and everything looks OK for me. And I think that the new model should minimize undefined-variable errors like what you're seeing here.

**Comment by astrofrog** [comment]
This is with the latest stable PyWWT

**Comment by astrofrog** [comment]
I will try the latest developer version in a few hours!

**Comment by pkgw** [comment]
Cool. The new setup should be much more robust long-term, I think, but it is new work so we'll see if there are any bugs that need to be shaken out ...

**Comment by astrofrog** [comment]
This is indeed fixed in the developer version. Weirdly if I pip install the latest dev version from git the version is wrong:

```
Successfully installed pywwt-0.0.0.dev0
```

But that's for another issue. In the mean time I'll close this as already fixed. Thanks!

**Comment by pkgw** [comment]
@astrofrog FWIW that version number is actually intended; it's part of the release automation scheme that I developed last summer, with the key ideas described here:

https://pkgw.github.io/cranko/book/latest/jit-versioning/index.html

It does lead to some unusual things like 0.0.0 version numbers but I have been fantastically happy with the approach! It addresses some key things about the release process that have been bothering me for literally more than a decade.
