### ISSUE TITLE
Reinstate wwt_ready qt signal

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#306]
It looks like the ``wwt_ready`` Qt Signal has been removed:

https://github.com/WorldWideTelescope/pywwt/blob/2c625d773cc803c9067b3fc67b0f4b19e58d043a/pywwt/qt.py#L70

This was very useful in glue-wwt to avoid having to use block_until_ready which blocked the whole glue UI. Currently glue-wwt is broken with the latest PyWWT as a result. Could we re-instate this signal?

**Comment by pkgw** [comment]
Oh, I didn't realize that it was used externally. (Once you get used to languages that give you more control to define what your public API is, Python gets more and more annoying!) I can easily put it back.
