### ISSUE TITLE
Add option for galactic mode

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#44]
There is an undocumented setting called ``galacticMode`` in WWT that can be set to True/False and determines whether the galactic plane should be horizontal in the viewer. This is a really useful option, and we should add it even though it isn't the official API docs.

**Comment by ojustino** [comment]
Are there more undocumented settings like this one?

**Comment by astrofrog** [comment]
@ojustino - I'm not sure! I'll try and investigate.

In any case, this was done in #46, so closing - thanks!
