### ISSUE TITLE
wwt widget not show (jupyter)

### ISSUE THREAD

**Issue by fandongwei** [WorldWideTelescope/pywwt#62]
I install the pywwt by code on github, then run the sample pywwt\examples\jupyter\example.ipynb, but the wwt widget does not show

The jupyter shows logs below:
[W 08:08:01.728 NotebookApp] 404 GET /static/ipyevents.js?v=20180124080622 (::1) 2.01ms referer=http://localhost:8888/notebooks/wwt/example.ipynb
[W 08:08:01.730 NotebookApp] 404 GET /static/pywwt.js?v=20180124080622 (::1) 1.01ms referer=http://localhost:8888/notebooks/wwt/example.ipynb

where can I download the ipyevents.js & pywwt.js? then where should I put them?
thanks

**Comment by philrosenfield** [comment]
Have you installed the nbextensions? In case you haven’t, have a look at this section of the docs: https://pywwt.readthedocs.io/en/latest/installation.html#installing-the-developer-version

**Comment by fandongwei** [comment]
I reinstalled my Anaconda python enviroment, then reinstall the pywwt, now everything goes well... 
don't know why. 
thanks

**Comment by philrosenfield** [comment]
Ok, great to hear it's working! Looking forward to seeing what you'll do :)
