### ISSUE TITLE
WWTJupyterWidget object has no attribute 'render'

### ISSUE THREAD

**Issue by JosephKarpinski** [WorldWideTelescope/pywwt#72]
http://pywwt.readthedocs.io/en/latest/settings.html

Screenshots like the one above are saved through a widget method that takes your desired file name its argument:

wwt.render('stgo_view.png')

AttributeError: 'WWTJupyterWidget' object has no attribute 'render'

**Comment by ojustino** [comment]
For now, it's only possible to save screenshots through the Qt version. We're working on extending that capability to Jupyter as well.

If you copy and save the code that led to your image in a local file and follow the instructions [here](http://pywwt.readthedocs.io/en/latest/qt.html?highlight=script), you can generate and save your image through one terminal call to `python FILENAME.py`.

**Comment by JosephKarpinski** [comment]
Thanks!
