### ISSUE TITLE
Make it so that FITS image stretch can be controlled from pywwt

### ISSUE THREAD

**Issue by astrofrog** [WorldWideTelescope/pywwt#85]
At the moment we can load FITS files into WWT via pywwt, but we have no control over the limits/stretch. We should make it so that users can set this. It might be nice for ``load_fits_data`` to return some kind of Image object that users can interact with.

**Comment by ojustino** [comment]
This issue is cross-linked with #113.

**Comment by astrofrog** [comment]
Implemented in https://github.com/WorldWideTelescope/pywwt/pull/188
