### ISSUE TITLE
Resolve libpng warning

### ISSUE THREAD

**Issue by ojustino** [WorldWideTelescope/pywwt#94]
Upon startup while using the Qt version, the error `libpng warning: gAMA: gamma value out of range` is printed several times.

(`libpng warning: iCCP: known incorrect sRGB profile` also appears from time to time while in solar system mode.)

It seems to be caused by the loading of the images used for the showConstellationPictures setting, and from some Googling it seems like the error is a problem with Qt, though I don't know exactly what. ~If it's not fixable, we could at least hide it by using the `javaScriptConsoleMessage()` function `qt.py` by adding `libpng not in message` to the `if` condition.~

**Comment by astrofrog** [comment]
See https://github.com/WorldWideTelescope/wwt-web-client/issues/177 for the gamma issue

**Comment by astrofrog** [comment]
@ojustino will investigate whether we can hide the warnings in the mean time.

**Comment by ojustino** [comment]
You were right that the warnings aren't coming from the JS console, so my method of muting them didn't work. After some more searching it seems like the only way to get rid of this error is to fix the png files that are causing it in the first place, confirming that this is an upstream issue.

**Comment by pkgw** [comment]
Closing this since this is basically out of pywwt's hands, and WorldWideTelescope/wwt-web-client#177 captures the bug in the right place.
